/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 05.05.2026 21:47:37

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 8448;
#else
constexpr int kTensorArenaSize = 7424;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3168 } };
const TfArray<1, float> quant0_scale = { 1, { 0.003216911805793643, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 32, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[6] = { 519, -548, 487, -653, -641, -324, };
const TfArray<1, int> tensor_dimension6 = { 1, { 6 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00034958581090904772, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[6*400] = { 
  11, 20, 32, -21, -11, 22, 13, 26, -28, -28, -5, 32, 6, 12, -36, 22, 15, 10, 5, -42, -46, 10, -18, 19, -18, -60, -3, 15, 28, 10, -37, 8, 1, 13, -16, -52, -18, 1, -40, -1, -33, -34, 26, 11, -13, -9, -56, 17, -12, 3, -1, -50, 4, 2, -5, 9, -6, -10, 11, 5, 11, 17, -28, -8, 12, 4, 14, -15, -2, 9, 20, 7, 17, -24, 22, 25, 7, 2, -5, 18, -7, 9, -8, -30, -24, 2, 10, 20, 16, 18, 17, 2, -4, -6, 8, 3, 8, 4, 11, -22, 13, 6, 13, 20, 13, 3, 6, 10, 9, 11, 25, -12, 4, 11, -7, -41, -12, 13, 45, 14, -17, 2, 18, 0, 18, 12, 29, -4, 3, 16, -12, -50, -21, 19, -46, 17, -20, 13, 9, 21, 7, 6, 17, -12, -3, 20, 0, -32, -11, 12, -11, 26, 1, 14, 5, 23, 14, -7, 26, 20, 11, 10, 19, -56, -9, -1, 0, 8, -24, 11, 3, 15, 1, -3, 16, 5, -11, -1, -2, -43, -57, 15, -18, 4, -13, 11, 18, 7, 27, -6, -23, -2, -2, 5, 4, -30, 8, 6, -10, 23, 1, -9, 2, 8, -3, -5, 1, 0, 18, 3, 10, -35, -27, 14, 7, 28, -23, -13, 7, 8, 17, -8, 9, 1, -5, 15, 0, -51, -29, -2, -23, -7, -20, -25, 6, 11, -1, 5, -3, 8, 1, 8, -19, -50, 13, 7, -38, 2, -23, -33, 16, 2, -37, 9, -22, -5, -2, 18, 13, -24, -3, 4, 10, 14, 35, -6, 17, 14, 12, -1, -12, 14, -2, 14, 9, -22, -20, 6, 17, 26, 15, -13, 9, 15, 16, 13, 9, -4, -4, 3, 4, -21, 6, 13, 3, 19, 24, -6, 5, 15, 16, 6, -16, -1, 19, 16, 13, -12, 5, 11, 29, 3, 1, -5, 9, 14, 7, 2, 7, 3, 1, 2, 0, -34, -23, 10, -12, -3, -26, -19, 12, 8, 20, -4, -7, 3, -3, 21, 3, -20, -36, 18, -29, 20, -21, 7, 3, 13, 0, 20, 15, -5, 4, 32, 10, -37, -30, 4, -21, 5, -32, -25, 7, 12, 12, -2, -7, 19, -1, 6, 16, -39, -14, 15, -8, 11, -30, -4, 13, 1, 1, -2, -27, -1, 1, 11, -2, -20, 0, 5, -32, 14, 8, -1, 3, 5, 17, 7, -8, 10, 
  6, -28, -1, 12, -9, -26, 7, 5, 11, -5, -20, -43, 6, -4, -8, 1, 14, -59, 17, 18, -48, -56, -15, 4, 27, -13, -29, -51, -9, -55, -36, -18, 15, -71, 16, 17, -24, -44, 4, -12, -10, -8, -24, -70, 3, -38, 9, -20, 10, -51, 14, -5, -31, -73, -6, 9, -18, 0, -31, -55, -13, -57, 1, -23, 8, -44, 9, 18, -40, -48, 8, 20, 4, 4, -36, -63, -12, -56, -30, -22, 13, -58, 11, 33, -57, -61, 12, 28, 19, -4, -43, -47, -14, -50, -18, -25, -2, -55, 22, 17, -89, -55, -3, -3, 12, -13, -36, -58, -20, -35, -17, -18, -5, -53, 3, 12, -35, -54, 2, 9, -3, 3, -35, -54, -14, -31, 5, -27, 13, -66, 12, 15, -16, -79, -7, 6, 9, -9, -30, -75, 5, -57, -5, -27, 9, -62, 0, 8, -37, -58, 17, 5, 8, -16, -29, -87, 1, -52, -1, -21, 2, -59, 14, 18, -57, -50, -10, 2, 40, 4, -38, -54, -8, -42, -20, -15, -13, -23, 26, 13, -47, -42, 5, -9, 15, 1, -33, -36, -10, -46, -1, -9, -2, -37, 8, 5, -15, -50, 6, 16, 4, 2, -20, -29, 3, -51, -1, -19, 9, -78, 16, 18, -35, -41, 8, 22, 3, -1, -23, -68, -2, -41, 0, -28, 2, -57, 4, 18, -47, -46, 1, 12, 36, -14, -26, -50, 5, -68, -36, -15, 11, -61, 3, 10, -50, -74, 7, 13, 11, -15, -32, -75, -8, -41, -3, -1, 18, -69, 14, 10, -51, -59, 18, -5, -9, -5, -31, -73, 1, -28, -2, -5, -5, -65, 15, 33, -54, -51, 1, 10, 27, 2, -35, -59, -2, -67, 9, -33, 6, -40, 7, 8, -47, -44, 9, 11, 22, -13, -32, -39, 19, -57, -14, -22, 16, -40, 28, 15, -41, -56, -8, -6, -2, -9, -28, -51, -24, -49, -3, -23, 9, -61, 9, 14, -29, -63, 3, 4, 3, 6, -30, -72, -3, -58, 10, -5, 9, -61, 15, 1, -35, -65, 3, -18, 1, -4, -49, -81, -35, -79, -6, -12, 2, -76, 23, 18, -61, -59, 5, 16, 1, -16, -18, -71, -5, -43, 0, -2, 10, -29, 9, 28, -64, -35, -10, -2, 58, -1, -15, -27, -7, -24, -15, -8, -8, -11, 4, 14, -50, -22, -5, 3, 32, -6, -5, 2, 11, -57, 0, -16, 
  -68, 17, -127, -33, 10, 17, -45, -81, 8, 16, 27, 13, -68, 3, 14, -16, -45, 2, -85, 19, 27, 7, 51, -48, 7, 30, 16, -4, -35, 20, 59, -8, -27, -4, -87, 13, 0, 3, 38, -39, 6, 39, -3, 6, -21, 15, 48, -7, -22, 13, -67, 51, 10, -6, 11, -16, 1, 31, 7, 19, -25, 22, 28, -4, -7, 6, -66, 49, -3, 5, 15, -34, -6, 22, 8, 16, -31, 18, 10, -7, -1, 6, -41, 35, 10, 4, -17, -46, -7, 4, 7, 21, -29, 19, -18, 8, -10, 11, -48, 17, -16, 10, -23, -48, -33, 4, 8, 4, -2, 11, -20, 7, -22, 12, -84, 31, 1, 8, -20, -74, 8, -18, 14, 5, -28, 18, -2, -11, -39, 20, -55, 58, -10, 1, -7, -61, 8, -16, 2, 3, -43, 9, -52, -7, -3, 15, -71, 35, 1, 12, -59, -82, -1, -42, -6, 17, -10, 17, -75, 14, 3, 11, -52, 25, 15, 4, -26, -44, -17, -20, 14, 6, -15, 12, -29, 4, 6, 16, -56, 35, -38, 11, 5, -56, -5, -1, 11, 8, 2, 17, 4, 8, -31, 15, -76, 39, -18, 10, 0, -29, -8, -15, 17, 5, -38, 9, -3, 20, -31, 14, -52, 59, -9, 13, -5, -10, 27, 10, 26, 9, -22, 8, 3, -2, -43, 5, -73, 41, 16, 1, 19, -17, 30, 37, 18, 13, -32, 24, 23, 19, -28, 8, -84, 39, -2, 18, 21, -17, 11, 22, 14, 8, -30, 25, 38, -2, -29, 19, -69, 48, -6, 25, -1, -31, -3, 1, -4, 26, -33, 7, 20, 15, -30, -9, -73, 48, 14, -2, 2, -72, -22, 18, 17, 7, -51, -10, 17, -8, 1, 2, -47, 34, -5, -9, -3, -54, -18, -1, 6, -3, -23, 9, 1, 1, -26, 13, -71, 38, -23, 14, -23, -57, -2, -11, 15, 7, -41, 24, -14, 11, -38, 7, -79, 35, -1, 10, -12, -64, 14, -12, 0, -2, -47, 27, -25, -10, -10, 8, -40, 51, -4, 13, -31, -45, -14, -16, 4, 6, -31, 13, -49, 11, -3, 8, -47, 25, 16, 3, -28, -48, -21, -31, 15, 8, -1, 5, -38, 4, -23, 12, -73, 30, -24, -3, -15, -42, -23, -32, 16, 8, -17, 21, -31, 17, -17, 13, -73, 34, 11, 12, -27, -58, -31, -22, 7, 20, -37, 4, -36, -8, 
  7, -10, -19, -20, 16, -4, -15, 5, -6, 10, 10, -13, -5, -7, 6, -14, 1, -2, -10, -6, 14, 18, -14, -3, 6, -4, 9, 0, -13, -1, -10, -19, 22, 18, 8, -20, 4, 6, 6, 29, 0, -1, -4, 0, 31, 0, 9, -6, 13, 12, 3, -15, -5, 20, 2, 0, 0, -16, 0, 0, 13, -33, -25, 18, -3, 11, -28, -80, -2, 8, -16, -5, -26, 7, 0, -6, -7, 12, -8, -11, 14, -2, -17, -59, 24, 16, 3, 3, -34, 7, -13, -8, 18, 8, 6, 4, 16, 10, -20, -32, 4, 10, 5, 12, -18, 14, 6, -2, 17, -14, -6, 22, -9, 17, -6, -24, 33, 9, -30, 0, 17, -8, -4, 23, 2, -3, 0, 17, 7, 4, -20, -31, 21, 6, 43, 5, -9, 7, -17, -10, -1, -10, 16, 19, -12, -37, -32, -15, 0, -14, 47, 9, -24, 16, 7, -26, 4, -14, 6, -37, -18, 10, -10, 20, -9, 6, 26, 9, 23, 12, 1, 14, 18, 22, 12, 3, -6, 0, 1, -1, 76, 2, 5, 23, 14, 9, 11, 11, -11, 9, 6, -7, 1, -1, -28, -40, 1, -6, 8, -4, -10, -3, -5, -10, 23, -11, 3, 10, 1, -8, -25, -21, 30, 12, -17, -4, 9, 0, 11, -2, 9, 2, -7, -11, 10, 10, 0, -14, 19, 11, 7, 20, 1, -3, 11, -5, 9, 12, -3, 11, 34, 2, 0, -8, -39, 13, 28, -5, -2, -9, -16, 15, 32, -6, -5, 23, 0, -6, -30, -76, -9, 14, -11, 2, -18, -9, 8, -1, -4, -4, 8, -11, 10, 16, -21, -55, 5, 11, -10, -4, -11, -6, -2, 0, 7, 5, 4, 12, -4, 6, -17, -40, -5, 16, 4, -7, -15, 0, 0, -16, 7, -4, -1, 19, -2, 5, -17, -49, -3, 23, -17, 3, 9, 7, 4, 18, 11, 4, -5, 3, 1, 12, 6, -33, 12, 5, 9, 11, 20, 18, 7, 3, -9, 2, 4, 9, 15, -6, -28, -58, 21, -16, 43, -4, -12, 28, -1, -19, 19, -19, -5, -14, -1, -15, -26, -8, 21, 11, 15, 2, 31, 28, -1, 0, -3, 0, 22, -22, -4, 8, -35, -12, 49, 6, 12, -5, 34, 24, 7, 18, 21, 2, 32, 4, -2, 3, -4, -12, -6, -8, 26, 12, 8, 9, 15, 3, 3, 4, 13, -10, 
  13, -22, 7, 18, -44, -37, -14, 20, 36, -4, -60, -25, 5, -6, -40, -7, -24, -27, 12, 16, -61, -42, -69, 31, 31, -15, -45, -2, -1, -90, -9, 2, -20, -13, 11, 35, -49, -20, -44, -2, 29, -20, -45, 21, -14, -70, -6, -4, -29, 15, 9, 27, -70, -18, -65, 20, 27, -9, -47, 11, -12, -72, -14, -12, -16, -26, 6, 8, -54, -27, -50, 15, 38, 4, -45, -21, 0, -83, -14, 8, -19, -6, 0, 13, -42, -25, -80, -9, 27, 6, -35, -13, -4, -87, -8, 10, -22, -34, 6, 34, -37, -25, -46, 3, 9, -9, -62, -35, -5, -72, -6, 9, -14, -23, 19, 18, -74, -25, -48, -2, 32, 5, -58, -12, -28, -75, -14, -7, -33, -16, 1, 33, -49, -28, -87, 23, 34, -15, -56, -16, -9, -79, -14, -9, -25, -22, 11, 18, -53, -36, -76, 8, 31, -20, -62, -21, -12, -71, -50, 15, -19, -8, 3, 14, -18, -39, -84, 2, 7, -26, -50, -9, -19, -74, -35, 3, -7, -25, 8, 11, -61, -51, -58, 7, 1, 6, -60, -26, -3, -60, -4, 5, -15, -18, 5, 15, -92, -33, -80, -2, 12, -25, -51, -13, -3, -61, -24, -14, -29, 11, 10, 40, -24, -27, -69, 18, 39, -17, -57, 11, -25, -80, -15, -2, -16, -13, 16, 9, -41, -44, -70, -3, 11, 1, -41, -15, 5, -68, -12, 10, -31, -25, 18, 18, -60, -25, -53, 20, 24, -15, -35, -11, -11, -75, -18, -2, -21, -20, 30, 23, -69, -35, -77, 30, 17, 4, -55, -1, -18, -76, -6, 14, -18, -28, 9, 22, -58, -35, -59, 16, 36, -9, -34, -1, 3, -64, -17, -16, -33, -14, 18, 33, -35, -41, -65, 24, 24, -8, -35, -23, -4, -65, -7, 10, -28, -32, 7, 9, -56, -31, -84, 12, 23, -6, -57, -5, -14, -79, -12, 5, -20, -23, 7, 26, -59, -41, -98, 16, 17, -6, -44, 14, -7, -88, -18, 7, -13, -29, 21, 10, -51, -37, -69, 24, 36, -21, -63, -20, -9, -61, -38, -4, -27, -21, 12, 20, -38, -47, -71, 8, 18, -8, -45, -3, -7, -70, -25, 3, -21, -32, 22, 27, -46, -38, -81, 25, 24, -19, -61, -22, -1, -91, -23, 3, -22, -36, 22, 15, -54, -35, -37, -1, 12, 0, -25, -16, -4, -95, -17, -27, 
  12, -34, -1, -3, -5, -67, 29, 0, -8, 13, -48, -49, 0, -4, 26, 3, 15, -30, 1, -6, 42, -38, 22, -38, -57, -19, -45, -47, -16, -66, 10, -11, 22, -23, 10, 6, 24, -39, 22, -22, -14, -31, -63, -36, -10, -61, -28, -4, -2, -44, 1, -4, 23, -42, 17, -14, -17, -30, -31, -33, -20, -80, -5, -16, -2, -47, 6, -9, 24, -41, 13, -16, -27, -10, -50, -43, -7, -64, 3, -6, 14, -17, 23, -7, 31, -22, 14, -4, -30, -18, -27, 1, -15, -44, -5, 4, 13, -16, 18, -1, 82, -14, 18, -6, -13, -19, -20, -13, -4, -54, -1, -1, 15, -28, 15, -1, 37, -27, 22, -5, -7, -21, -31, -27, 4, -62, -22, 1, 22, -40, 8, 4, 31, -9, 13, -15, -11, -14, -30, -42, -21, -29, -17, 4, 19, -11, -4, 6, 17, -26, 10, -6, -10, -7, -34, 21, -24, -35, -11, -8, 26, -51, -3, 2, 54, -59, 18, -3, -58, -10, -58, -42, -17, -58, 7, 6, 25, -62, 15, -15, 40, -60, 24, -13, -21, -16, -50, -65, -10, -55, 1, -4, 13, -59, -4, -12, 18, -60, 16, -6, -16, -4, -47, -58, -4, -63, 6, 12, 6, -51, 2, -20, 24, -62, 6, -53, -25, -20, -46, -48, -11, -73, -3, -14, 8, -30, -2, -16, 27, -35, 35, -14, -33, -16, -31, -47, -4, -30, 18, -2, 3, -5, 0, -2, 40, -36, 9, -14, -37, -19, -32, 6, 0, -37, -5, -13, 17, -35, 6, -6, 40, -41, 16, -23, -14, -9, -50, -19, -29, -75, -12, -20, 8, -19, 14, -19, 58, -49, 4, -10, -39, -15, -52, -32, -2, -74, -9, 14, 6, -63, 9, -2, 26, -51, 24, 1, -49, -17, -51, -57, -18, -57, 3, -3, -4, -17, 0, 7, 49, -30, 19, 2, -24, -7, -32, -40, 7, -84, -10, -3, 10, -26, 9, -7, 44, -45, 32, -7, -17, -12, -30, -24, 2, -54, -4, -7, 0, -18, 0, 8, 40, -10, 16, 13, -4, -14, -22, -5, -1, -19, 3, -5, 5, -3, 9, -7, 55, -31, 10, -6, -19, -10, -51, -14, -7, -78, 2, -18, 17, -78, 0, -14, 58, -63, 23, -11, -57, -8, -55, -73, -1, -67, -8, 6, 25, -74, 23, -15, 43, -67, 26, -6, -41, -11, -46, -93, -4, -91, -9, -5, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 6,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0099168559536337852, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -213, 2885, -930, 82, -192, 2618, -783, -1450, -2483, -1670, 2359, 1791, -1045, 2512, -177, -320, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 4.43923709099181e-05, 4.3722131522372365e-05, 7.9516830737702549e-05, 0.00010284972086083144, 7.395097054541111e-05, 4.6166238462319598e-05, 8.6494081187993288e-05, 7.0645735831931233e-05, 7.0336536737158895e-05, 4.9495585699332878e-05, 5.0439470214769244e-05, 7.0155736466404051e-05, 7.5705960625782609e-05, 5.4192099923966452e-05, 6.30715730949305e-05, 4.1027971747098491e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 127,77,101,11,-50,-9,8,55, 22,56,22,-24,-72,-16,123,-57, 17,72,26,-2,-67,-72,72,27, 
  /* [1][0][][] */ -99,90,-66,80,45,-79,-25,56, -125,-19,-75,-1,127,55,28,114, -43,5,-61,-54,-21,-84,5,-5, 
  /* [2][0][][] */ -20,-4,5,-13,14,-62,73,52, 30,-4,93,13,27,-69,88,101, -48,-5,80,-40,21,-52,127,46, 
  /* [3][0][][] */ -2,-104,31,-7,127,-8,-26,-5, 3,-102,28,24,90,-36,-30,-11, -40,-72,22,-29,119,-42,12,-11, 
  /* [4][0][][] */ 39,-57,3,-70,-104,-8,1,-15, 24,-50,14,-91,-90,51,16,-54, 111,36,66,-55,-127,83,13,-21, 
  /* [5][0][][] */ -76,98,-92,45,8,-83,-25,105, -86,37,-127,-22,59,35,-41,7, -34,125,-76,17,18,-3,-25,70, 
  /* [6][0][][] */ 127,-4,71,46,-77,5,31,-21, 71,-19,65,-9,-88,26,30,-12, 36,-31,14,44,-70,35,-28,-60, 
  /* [7][0][][] */ -44,31,-45,-43,21,32,85,75, 58,50,33,43,67,29,122,109, -27,8,-41,-14,69,5,127,93, 
  /* [8][0][][] */ 3,-40,37,55,84,13,41,36, -50,-61,-10,35,127,7,-31,62, -26,-44,29,30,77,17,-4,23, 
  /* [9][0][][] */ 4,-63,22,74,-88,68,-39,-5, -58,-87,-69,-46,-82,88,-100,-9, -49,-91,-44,80,-127,75,-95,9, 
  /* [10][0][][] */ -35,-29,-114,-14,64,-57,-7,-19, -34,-34,-106,2,-9,-28,-90,16, 33,10,-127,61,-9,53,-26,73, 
  /* [11][0][][] */ -92,34,-67,61,99,2,-20,29, -82,10,-51,-8,127,-61,-2,57, -47,-15,-62,-19,22,-61,10,32, 
  /* [12][0][][] */ 11,27,-48,31,-21,-10,127,42, 32,29,-72,-31,-32,11,-6,6, 18,8,-22,-28,5,-72,-41,46, 
  /* [13][0][][] */ 35,-15,-103,0,-27,38,-104,-53, 58,33,-122,25,-16,-78,-104,-55, -26,21,-23,-11,124,-66,-127,24, 
  /* [14][0][][] */ 58,-16,25,3,-79,81,-44,-98, -13,-13,34,37,-78,64,-30,-119, 9,-127,-35,73,-64,-27,-51,-87, 
  /* [15][0][][] */ 48,88,-59,0,21,-21,5,100, -11,-8,2,-34,20,-49,6,44, -127,-65,8,-62,-60,-12,11,30, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0037373711820691824, 0.0036809439770877361, 0.0066944817081093788, 0.0086588654667139053, 0.006225894670933485, 0.0038867122493684292, 0.007281892467290163, 0.0059476285241544247, 0.0059215971268713474, 0.004167008213698864, 0.0042464733123779297, 0.005906375590711832, 0.0063736462034285069, 0.0045624054037034512, 0.0053099635988473892, 0.0034541240893304348, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 572, 1674, -769, -17124, 260, -11955, 444, 362, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 2.5515711968182586e-05, 1.7955544535652734e-05, 2.0664267140091397e-05, 1.455669007555116e-05, 3.5238314012531191e-05, 1.7440517694922164e-05, 5.7093511713901535e-05, 3.935608037863858e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*32] = { 
  /* [0][0][][] */ 9,27,-9,-6,-50,-20,12,-63,-96,-60,-75,-25,-31,-123,-122,-84,-93,-43,-64,-15,59,19,-30,-42,3,-22,-35,-52,-18,-39,-77,-45, 1,12,58,41,24,-30,38,0,-38,-7,-51,49,7,-62,-14,-18,-12,43,58,111,96,92,17,3,58,13,10,34,-13,24,-18,-29, -7,13,61,27,24,-19,-25,-21,-71,-20,-61,-40,-67,-98,-127,-68,-25,53,84,23,72,-50,-99,-90,-43,-21,-44,-72,-33,-64,-74,-63, 
  /* [1][0][][] */ -89,-79,26,65,13,78,2,35,5,18,-3,-18,114,-29,6,-15,-77,-78,-27,-2,-26,-57,-25,-51,-37,-55,-67,-28,-36,-19,-75,-127, -59,-11,75,80,31,9,34,-24,39,19,-15,26,81,63,6,19,-30,-54,-55,-26,7,-49,-54,5,-11,-37,-30,-9,14,27,-73,-83, -64,-31,54,26,25,75,15,-10,6,60,22,9,55,6,-31,-56,5,-75,-63,-62,-69,-7,-2,-29,-57,1,-52,26,26,-35,-74,-91, 
  /* [2][0][][] */ 58,66,-18,-14,-59,-54,0,23,-25,-26,-31,-34,-39,-127,-105,-75,-75,-69,-29,14,83,11,-32,-41,9,-53,-81,-67,-5,-32,-45,5, -19,52,97,32,29,-41,-11,-3,7,-18,-15,-15,-4,-48,-27,-56,-13,-43,11,-4,42,48,54,20,17,3,44,45,30,60,4,26, 5,68,32,35,-32,-66,-28,31,-17,-4,-43,0,-73,-57,-117,-107,-74,-75,-74,-11,71,2,-9,-24,12,-51,-72,-48,-1,1,-17,-8, 
  /* [3][0][][] */ 5,17,18,-45,58,-18,-21,-36,-10,-37,18,-16,10,25,25,-19,32,-17,4,-20,-14,15,36,33,-20,-2,10,-64,77,45,54,127, 58,60,72,47,24,-2,-68,36,-60,-9,39,15,75,48,76,-28,37,7,-41,-33,-52,-63,30,-50,0,-11,-46,-15,42,23,8,122, -12,-23,54,-13,70,14,7,44,-4,25,30,34,49,16,76,-2,46,-14,38,-60,0,5,-3,-18,-89,-34,5,-76,-34,17,-42,80, 
  /* [4][0][][] */ 26,-19,-11,19,-12,-16,-53,30,26,-19,-42,11,56,69,59,65,15,-54,-36,-81,-112,-95,-38,-1,-58,-61,-47,1,57,53,68,89, -7,-17,-4,-16,-3,2,-53,17,27,-13,8,-5,30,51,85,31,31,-44,-51,-80,-107,-81,-75,-67,-91,-68,-60,-74,-10,42,84,93, 13,10,-14,-12,8,-7,-70,28,-1,-47,-16,1,35,61,43,42,52,-78,-55,-81,-127,-98,-39,-41,-77,-59,-63,-4,48,67,54,93, 
  /* [5][0][][] */ 1,16,-34,-23,-5,-8,-42,-12,-37,55,32,61,38,80,26,21,-45,8,7,36,-1,-11,41,-51,-48,-90,-49,-43,-75,3,-68,96, 27,3,10,-19,-14,-9,34,-19,-53,23,87,71,70,59,30,6,-22,-9,-7,-14,20,50,5,-3,-31,-48,1,1,9,-27,20,127, -15,37,-54,1,-7,14,-39,-26,-54,61,22,25,57,98,33,-17,20,-38,42,-3,14,9,-7,-30,-28,-14,-26,-38,-39,2,-41,98, 
  /* [6][0][][] */ 4,9,12,8,2,-23,-21,-24,-24,-25,-31,11,101,3,-29,-22,-28,-8,-27,-9,-24,-5,-16,-45,-35,-11,-15,-10,1,-11,-43,-65, -5,-1,26,27,-10,1,-15,-20,-15,-14,-7,-5,82,45,-8,9,-15,-7,-22,19,-12,4,2,-40,-20,-7,-2,13,3,-10,-34,-46, -13,15,27,12,-12,-19,-10,-9,-18,5,-28,9,127,23,-33,-14,-26,-30,-46,-12,-27,-24,-21,-51,-7,8,-24,-6,6,-5,-42,-61, 
  /* [7][0][][] */ 10,-14,10,4,11,5,-26,5,7,-10,9,-16,127,18,-15,10,-15,-13,-38,-25,-46,-24,-31,-48,-32,-18,-18,6,-1,5,-31,-41, 6,9,9,-5,18,0,-7,-6,8,-1,-18,-2,103,35,6,20,-14,-31,-39,-52,-42,-44,-44,-61,-62,-21,-23,-15,-17,-11,-28,-43, 2,-14,0,17,-1,-18,-38,-16,12,-9,-6,-4,127,47,-25,-4,-13,-44,-58,-50,-66,-49,-29,-44,-42,-7,-31,7,-22,-6,-37,-42, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,32 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0079317409545183182, 0.0055816094391047955, 0.0064236349426209927, 0.0045250509865581989, 0.010954081080853939, 0.005421509500592947, 0.017747925594449043, 0.012234118767082691, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,32 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.011877967044711113, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.0352516770362854, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,6 } };
const TfArray<1, float> quant21_scale = { 1, { 0.24792695045471191, } };
const TfArray<1, int> quant21_zero = { 1, { 65 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3168), (TfLiteIntArray*)&g0::tensor_dimension0, 3168, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 2400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 768, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3168, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3168), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_985961_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_985961_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_985961_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_985961_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_985961_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
